/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as GuestSignUpRouteImport } from './routes/_guest/sign-up'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as GuestHomeRouteImport } from './routes/_guest/home'
import { Route as GuestAboutRouteImport } from './routes/_guest/about'
import { Route as ProtectedUserIndexRouteImport } from './routes/_protected/user/index'
import { Route as ProtectedDocumentIndexRouteImport } from './routes/_protected/document/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'

const GuestForgotPasswordLazyRouteImport = createFileRoute(
  '/_guest/forgot-password',
)()

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestForgotPasswordLazyRoute = GuestForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any).lazy(() =>
  import('./routes/_guest/forgot-password.lazy').then((d) => d.Route),
)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignUpRoute = GuestSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRoute,
} as any)
const GuestHomeRoute = GuestHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAboutRoute = GuestAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => GuestRoute,
} as any)
const ProtectedUserIndexRoute = ProtectedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDocumentIndexRoute = ProtectedDocumentIndexRouteImport.update({
  id: '/document/',
  path: '/document/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof GuestAboutRoute
  '/home': typeof GuestHomeRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/api/test': typeof ApiTestRoute
  '/forgot-password': typeof GuestForgotPasswordLazyRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/document/': typeof ProtectedDocumentIndexRoute
  '/user/': typeof ProtectedUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof GuestAboutRoute
  '/home': typeof GuestHomeRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/api/test': typeof ApiTestRoute
  '/forgot-password': typeof GuestForgotPasswordLazyRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/document': typeof ProtectedDocumentIndexRoute
  '/user': typeof ProtectedUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest': typeof GuestRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_guest/about': typeof GuestAboutRoute
  '/_guest/home': typeof GuestHomeRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_guest/sign-up': typeof GuestSignUpRoute
  '/api/test': typeof ApiTestRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordLazyRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/document/': typeof ProtectedDocumentIndexRoute
  '/_protected/user/': typeof ProtectedUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/home'
    | '/sign-in'
    | '/sign-up'
    | '/api/test'
    | '/forgot-password'
    | '/dashboard/'
    | '/document/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/home'
    | '/sign-in'
    | '/sign-up'
    | '/api/test'
    | '/forgot-password'
    | '/dashboard'
    | '/document'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/_guest'
    | '/_protected'
    | '/_guest/about'
    | '/_guest/home'
    | '/_guest/sign-in'
    | '/_guest/sign-up'
    | '/api/test'
    | '/_guest/forgot-password'
    | '/_protected/dashboard/'
    | '/_protected/document/'
    | '/_protected/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRoute: typeof GuestRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiTestRoute: typeof ApiTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordLazyRouteImport
      parentRoute: typeof GuestRoute
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/sign-up': {
      id: '/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof GuestSignUpRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/home': {
      id: '/_guest/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof GuestHomeRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/about': {
      id: '/_guest/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof GuestAboutRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_protected/user/': {
      id: '/_protected/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof ProtectedUserIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/document/': {
      id: '/_protected/document/'
      path: '/document'
      fullPath: '/document/'
      preLoaderRoute: typeof ProtectedDocumentIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface GuestRouteChildren {
  GuestAboutRoute: typeof GuestAboutRoute
  GuestHomeRoute: typeof GuestHomeRoute
  GuestSignInRoute: typeof GuestSignInRoute
  GuestSignUpRoute: typeof GuestSignUpRoute
  GuestForgotPasswordLazyRoute: typeof GuestForgotPasswordLazyRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestAboutRoute: GuestAboutRoute,
  GuestHomeRoute: GuestHomeRoute,
  GuestSignInRoute: GuestSignInRoute,
  GuestSignUpRoute: GuestSignUpRoute,
  GuestForgotPasswordLazyRoute: GuestForgotPasswordLazyRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDocumentIndexRoute: typeof ProtectedDocumentIndexRoute
  ProtectedUserIndexRoute: typeof ProtectedUserIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDocumentIndexRoute: ProtectedDocumentIndexRoute,
  ProtectedUserIndexRoute: ProtectedUserIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRoute: GuestRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiTestRoute: ApiTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
